export default {
  LoginVariant: require("@icon/LoginVariant").default,
  AccountCircle: require("@icon/AccountCircle").default,
  HospitalBuilding: require("@icon/HospitalBuilding").default,
  Plus: require("@icon/Plus").default,
  Magnify: require("@icon/Magnify").default,
  Delete: require("@icon/Delete").default,
  Update: require("@icon/Update").default,
  EyeOutline: require("@icon/EyeOutline").default,
  EyeOffOutline: require("@icon/EyeOffOutline").default,
  SquareEditOutline: require("@icon/SquareEditOutline").default,
  AccountBox: require("@icon/AccountBox").default,
  AccountClock: require("@icon/AccountClock").default,
  Forum: require("@icon/Forum").default,
  CurrencyUsd: require("@icon/CurrencyUsd").default,
  ArrowLeft: require("@icon/ArrowLeft").default,
  ArrowLeftCircle: require("@icon/ArrowLeftCircle").default,
  Information: require("@icon/Information").default,
  CheckCircle: require("@icon/CheckCircle").default,
};
